/* =========================================================
   STUDYMIND AI — COMPUTER BATTLE
   AI-GENERATED CURRICULUM QUESTIONS ONLY

   IMPORTANT:
   - NO hard-coded question bank
   - Questions are generated by the AI
   - Subject + topic are sent to the AI
   - Questions are validated against the selection
   - Exactly 10 questions per battle
   - 15 seconds per question
========================================================= */


/* =========================================================
   CONFIGURATION
========================================================= */

const QUESTIONS_PER_BATTLE = 10;
const QUESTION_TIME_LIMIT = 15;

const AI_QUESTION_ENDPOINT = "/api/generate-questions";

const FREE_BATTLE_LIMIT = 5;


/* =========================================================
   NIGERIAN / SENIOR SECONDARY CURRICULUM TOPICS

   This is NOT a question bank.

   These are curriculum references used to tell the AI
   what areas it is allowed to generate questions from.
========================================================= */

const NIGERIAN_CURRICULUM = {

    "Mathematics": [
        "Number Bases",
        "Fractions, Decimals and Percentages",
        "Indices",
        "Logarithms",
        "Surds",
        "Sets",
        "Algebraic Expressions",
        "Linear Equations",
        "Quadratic Equations",
        "Simultaneous Equations",
        "Inequalities",
        "Sequences and Series",
        "Variation",
        "Polynomials",
        "Functions",
        "Coordinate Geometry",
        "Geometry",
        "Mensuration",
        "Trigonometry",
        "Statistics",
        "Probability",
        "Vectors",
        "Matrices",
        "Commercial Mathematics",
        "Financial Mathematics"
    ],

    "English Language": [
        "Comprehension",
        "Summary Writing",
        "Grammar",
        "Parts of Speech",
        "Sentence Structure",
        "Concord",
        "Tenses",
        "Clauses",
        "Phrases",
        "Vocabulary Development",
        "Synonyms",
        "Antonyms",
        "Idioms",
        "Registers",
        "Oral English",
        "Speech Sounds",
        "Stress",
        "Intonation",
        "Lexis and Structure",
        "Essay Writing",
        "Formal Writing",
        "Informal Writing",
        "Letter Writing",
        "Report Writing",
        "Article Writing",
        "Argumentative Writing",
        "Narrative Writing"
    ],

    "Physics": [
        "Measurement",
        "Scalars and Vectors",
        "Motion",
        "Speed and Velocity",
        "Acceleration",
        "Newton's Laws of Motion",
        "Momentum",
        "Work Energy and Power",
        "Simple Machines",
        "Pressure",
        "Heat",
        "Temperature",
        "Thermal Expansion",
        "Waves",
        "Sound",
        "Light",
        "Reflection",
        "Refraction",
        "Electricity",
        "Current Electricity",
        "Electrical Circuits",
        "Magnetism",
        "Electromagnetic Induction",
        "Electromagnetic Waves",
        "Atomic Physics",
        "Nuclear Physics",
        "Radioactivity",
        "Semiconductors"
    ],

    "Chemistry": [
        "Matter",
        "Atomic Structure",
        "Periodic Table",
        "Chemical Bonding",
        "Mole Concept",
        "Chemical Formulae",
        "Chemical Equations",
        "Stoichiometry",
        "States of Matter",
        "Gas Laws",
        "Solutions",
        "Acids Bases and Salts",
        "pH",
        "Oxidation and Reduction",
        "Electrochemistry",
        "Organic Chemistry",
        "Hydrocarbons",
        "Alkanes",
        "Alkenes",
        "Alkynes",
        "Alcohols",
        "Carboxylic Acids",
        "Esters",
        "Polymers",
        "Petroleum",
        "Metals",
        "Non-metals",
        "Qualitative Analysis",
        "Environmental Chemistry"
    ],

    "Biology": [
        "Characteristics of Living Things",
        "Cell Structure",
        "Cell Functions",
        "Cell Division",
        "Nutrition",
        "Photosynthesis",
        "Respiration",
        "Transport in Plants",
        "Transport in Animals",
        "Excretion",
        "Homeostasis",
        "Support and Movement",
        "Reproduction",
        "Growth",
        "Genetics",
        "Variation",
        "Evolution",
        "Ecology",
        "Food Chains",
        "Food Webs",
        "Population Studies",
        "Adaptation",
        "Microorganisms",
        "Diseases",
        "Classification",
        "Plant Biology",
        "Animal Biology",
        "Human Biology"
    ],

    "Further Mathematics": [
        "Logic",
        "Sets",
        "Functions",
        "Matrices",
        "Determinants",
        "Complex Numbers",
        "Polynomial Equations",
        "Sequences and Series",
        "Binomial Expansion",
        "Coordinate Geometry",
        "Vectors",
        "Differentiation",
        "Integration",
        "Differential Equations",
        "Permutations",
        "Combinations",
        "Probability",
        "Statistics",
        "Mechanics"
    ],

    "Agricultural Science": [
        "Agriculture",
        "Farm Management",
        "Soil Science",
        "Soil Fertility",
        "Crop Production",
        "Crop Improvement",
        "Crop Pests",
        "Crop Diseases",
        "Animal Production",
        "Animal Nutrition",
        "Animal Health",
        "Livestock Management",
        "Fisheries",
        "Forestry",
        "Agricultural Economics",
        "Farm Records",
        "Agricultural Extension",
        "Farm Tools and Machinery"
    ],

    "Geography": [
        "Map Reading",
        "Scale",
        "Map Interpretation",
        "Weather",
        "Climate",
        "Climate Change",
        "Rocks",
        "Minerals",
        "Weathering",
        "Erosion",
        "Mass Movement",
        "Rivers",
        "Drainage",
        "Coastal Processes",
        "Population",
        "Migration",
        "Settlement",
        "Urbanisation",
        "Agriculture",
        "Industry",
        "Transportation",
        "Trade",
        "Natural Resources",
        "Environmental Management",
        "Nigeria's Geography"
    ],

    "Government": [
        "Political Concepts",
        "Power",
        "Authority",
        "Legitimacy",
        "Democracy",
        "Political Participation",
        "Political Parties",
        "Pressure Groups",
        "Public Opinion",
        "Constitution",
        "Rule of Law",
        "Separation of Powers",
        "Checks and Balances",
        "Federalism",
        "Unitary Government",
        "Confederation",
        "Citizenship",
        "Human Rights",
        "Electoral Systems",
        "Electoral Bodies",
        "Public Administration",
        "Local Government",
        "Nigerian Political Development",
        "International Organisations",
        "Foreign Policy"
    ],

    "Nigerian History": [
        "Pre-colonial Nigerian Societies",
        "Kanem-Borno",
        "Hausa States",
        "Yoruba States",
        "Benin Kingdom",
        "Igbo Society",
        "Trans-Saharan Trade",
        "European Contact",
        "Slave Trade",
        "Christian Missions",
        "Colonial Administration",
        "Amalgamation",
        "Nationalism",
        "Independence",
        "First Republic",
        "Military Rule",
        "Civil War",
        "Second Republic",
        "Return to Democracy",
        "Contemporary Nigerian History"
    ],

    "Christian Religious Studies": [
        "Creation",
        "The Fall of Man",
        "Call of Abraham",
        "Covenant",
        "Moses",
        "The Ten Commandments",
        "Leadership",
        "Prophets",
        "Justice",
        "Faith",
        "Wisdom Literature",
        "Birth of Jesus",
        "Ministry of Jesus",
        "Miracles",
        "Parables",
        "Teachings of Jesus",
        "Death and Resurrection",
        "Early Church",
        "Christian Leadership",
        "Christian Ethics"
    ],

    "Islamic Religious Studies": [
        "Quran",
        "Hadith",
        "Tawhid",
        "Prophethood",
        "Prayer",
        "Fasting",
        "Zakat",
        "Hajj",
        "Islamic Ethics",
        "Islamic History",
        "Life of Prophet Muhammad",
        "Early Muslim Community",
        "Islamic Law",
        "Family Life in Islam",
        "Economic Principles in Islam",
        "Social Responsibilities"
    ],

    "Literature in English": [
        "Poetry",
        "Drama",
        "Prose",
        "Plot",
        "Characterisation",
        "Setting",
        "Theme",
        "Conflict",
        "Narrative Technique",
        "Point of View",
        "Figures of Speech",
        "Imagery",
        "Symbolism",
        "Irony",
        "Dramatic Techniques",
        "Poetic Devices",
        "Literary Genres",
        "African Literature",
        "Nigerian Literature"
    ],

    "Accounting": [
        "Introduction to Accounting",
        "Accounting Concepts",
        "Double Entry",
        "Ledger",
        "Trial Balance",
        "Cash Book",
        "Bank Reconciliation",
        "Control Accounts",
        "Final Accounts",
        "Depreciation",
        "Partnership Accounts",
        "Company Accounts",
        "Manufacturing Accounts",
        "Incomplete Records",
        "Accounting Ratios",
        "Public Sector Accounting"
    ],

    "Commerce": [
        "Trade",
        "Home Trade",
        "Foreign Trade",
        "Retail Trade",
        "Wholesale Trade",
        "Channels of Distribution",
        "Transportation",
        "Warehousing",
        "Insurance",
        "Banking",
        "Advertising",
        "Communication",
        "Business Documents",
        "Consumer Protection",
        "Stock Exchange",
        "Entrepreneurship"
    ],

    "Economics": [
        "Basic Economic Concepts",
        "Scarcity",
        "Choice",
        "Opportunity Cost",
        "Production",
        "Factors of Production",
        "Demand",
        "Supply",
        "Elasticity",
        "Market Structure",
        "Price Determination",
        "National Income",
        "Inflation",
        "Unemployment",
        "Money",
        "Banking",
        "Public Finance",
        "Taxation",
        "International Trade",
        "Economic Development",
        "Population",
        "Agriculture",
        "Industry",
        "Nigerian Economy"
    ],

    "Digital Technologies": [
        "Computer Fundamentals",
        "Hardware",
        "Software",
        "Operating Systems",
        "Data Representation",
        "Algorithms",
        "Programming",
        "Databases",
        "Networks",
        "Internet",
        "Cybersecurity",
        "Artificial Intelligence",
        "Digital Citizenship",
        "Cloud Computing",
        "Information Systems",
        "Data Management"
    ],

    "Computer Studies": [
        "Computer Fundamentals",
        "Computer Hardware",
        "Computer Software",
        "Operating Systems",
        "Data Processing",
        "Algorithms",
        "Flowcharts",
        "Programming",
        "Databases",
        "Computer Networks",
        "Internet",
        "Cybersecurity",
        "Computer Ethics"
    ],

    "Technical Drawing": [
        "Drawing Instruments",
        "Geometrical Construction",
        "Orthographic Projection",
        "Isometric Drawing",
        "Oblique Drawing",
        "Perspective Drawing",
        "Sections",
        "Development",
        "Engineering Curves",
        "Dimensioning",
        "Building Drawing",
        "Mechanical Drawing"
    ],

    "Visual Arts": [
        "Drawing",
        "Painting",
        "Sculpture",
        "Textiles",
        "Ceramics",
        "Graphic Design",
        "Art History",
        "African Art",
        "Nigerian Art",
        "Art Appreciation",
        "Design Principles"
    ],

    "Music": [
        "Music Theory",
        "Notation",
        "Scales",
        "Intervals",
        "Rhythm",
        "Melody",
        "Harmony",
        "Musical Instruments",
        "African Music",
        "Nigerian Music",
        "Music History",
        "Composition"
    ],

    "Physical Education": [
        "Physical Fitness",
        "Health Related Fitness",
        "Athletics",
        "Football",
        "Basketball",
        "Volleyball",
        "Handball",
        "Gymnastics",
        "Swimming",
        "First Aid",
        "Sportsmanship",
        "Nutrition and Exercise"
    ],

    "Health Education": [
        "Personal Health",
        "Community Health",
        "Nutrition",
        "First Aid",
        "Communicable Diseases",
        "Non-communicable Diseases",
        "Environmental Health",
        "Mental Wellbeing",
        "Drug Education",
        "Family Health",
        "Public Health"
    ],

    "Foods and Nutrition": [
        "Food Groups",
        "Nutrients",
        "Balanced Diet",
        "Meal Planning",
        "Food Preservation",
        "Food Preparation",
        "Food Safety",
        "Kitchen Equipment",
        "Consumer Education",
        "Nutrition and Health"
    ],

    "Home Management": [
        "Home Management",
        "Family Resources",
        "Decision Making",
        "Budgeting",
        "Consumer Education",
        "Housing",
        "Clothing",
        "Food Management",
        "Household Equipment",
        "Family Relationships"
    ],

    "Marketing": [
        "Marketing Concepts",
        "Market Research",
        "Product",
        "Price",
        "Promotion",
        "Place",
        "Advertising",
        "Sales Promotion",
        "Consumer Behaviour",
        "Distribution",
        "Branding",
        "Digital Marketing"
    ],

    "Citizenship and Heritage Studies": [
        "Citizenship",
        "National Identity",
        "Civic Responsibilities",
        "Human Rights",
        "Democracy",
        "National Values",
        "Cultural Heritage",
        "Nigerian Culture",
        "Peace Building",
        "Conflict Resolution",
        "National Unity",
        "Responsible Citizenship"
    ],

    "Basic Science": [
        "Living Things",
        "Matter",
        "Energy",
        "Force",
        "Motion",
        "Heat",
        "Light",
        "Sound",
        "Electricity",
        "Magnetism",
        "Environment",
        "Human Health"
    ],

    "Basic Technology": [
        "Technology",
        "Materials",
        "Tools",
        "Workshop Safety",
        "Drawing",
        "Woodwork",
        "Metalwork",
        "Building",
        "Electricity",
        "Mechanisms",
        "Machines"
    ],

    "French": [
        "Greetings",
        "Numbers",
        "Family",
        "School",
        "Food",
        "Time",
        "Dates",
        "Grammar",
        "Vocabulary",
        "Conversation",
        "Reading Comprehension",
        "Writing"
    ],

    "Arabic": [
        "Arabic Alphabet",
        "Vocabulary",
        "Grammar",
        "Reading",
        "Writing",
        "Comprehension",
        "Conversation",
        "Arabic Culture"
    ],

    "Yoruba": [
        "Grammar",
        "Vocabulary",
        "Reading",
        "Writing",
        "Oral Literature",
        "Proverbs",
        "Folklore",
        "Culture",
        "Yoruba Literature"
    ],

    "Igbo": [
        "Grammar",
        "Vocabulary",
        "Reading",
        "Writing",
        "Oral Literature",
        "Proverbs",
        "Folklore",
        "Culture",
        "Igbo Literature"
    ]

};


/* =========================================================
   SUBJECT ALIASES
========================================================= */

const SUBJECT_ALIASES = {

    "math": "Mathematics",
    "mathematics": "Mathematics",
    "general mathematics": "Mathematics",

    "english": "English Language",
    "english language": "English Language",

    "physics": "Physics",

    "chem": "Chemistry",
    "chemistry": "Chemistry",

    "bio": "Biology",
    "biology": "Biology",

    "further maths": "Further Mathematics",
    "further mathematics": "Further Mathematics",

    "agriculture": "Agricultural Science",
    "agricultural science": "Agricultural Science",

    "geography": "Geography",

    "government": "Government",

    "history": "Nigerian History",
    "nigerian history": "Nigerian History",

    "crs": "Christian Religious Studies",
    "christian religious studies": "Christian Religious Studies",

    "irs": "Islamic Religious Studies",
    "islamic religious studies": "Islamic Religious Studies",

    "literature": "Literature in English",
    "literature in english": "Literature in English",

    "accounting": "Accounting",

    "commerce": "Commerce",

    "economics": "Economics",

    "computer studies": "Computer Studies",
    "computer science": "Computer Studies",

    "digital technologies": "Digital Technologies",

    "technical drawing": "Technical Drawing",

    "visual arts": "Visual Arts",

    "music": "Music",

    "physical education": "Physical Education",

    "health education": "Health Education",

    "foods and nutrition": "Foods and Nutrition",

    "home management": "Home Management",

    "marketing": "Marketing",

    "citizenship and heritage studies":
        "Citizenship and Heritage Studies",

    "basic science": "Basic Science",

    "basic technology": "Basic Technology",

    "french": "French",

    "arabic": "Arabic",

    "yoruba": "Yoruba",

    "igbo": "Igbo"
};


/* =========================================================
   GLOBAL BATTLE STATE
========================================================= */

let battleState = {

    user: null,

    subject: "",

    topic: "",

    questions: [],

    currentQuestionIndex: 0,

    playerScore: 0,

    computerScore: 0,

    timer: null,

    timeRemaining: QUESTION_TIME_LIMIT,

    answered: false,

    battleStarted: false,

    battleId: null

};


/* =========================================================
   DOM HELPER
========================================================= */

function $(id) {

    return document.getElementById(id);

}


/* =========================================================
   SUPABASE
========================================================= */

function getComputerBattleSupabase() {

    if (
        window.supabaseClient &&
        window.supabaseClient.auth
    ) {
        return window.supabaseClient;
    }

    return null;

}


async function waitForSupabaseClient(timeout = 10000) {

    const start = Date.now();

    while (Date.now() - start < timeout) {

        const client = getComputerBattleSupabase();

        if (client) {
            return client;
        }

        await new Promise(resolve => {
            setTimeout(resolve, 100);
        });

    }

    return null;

}


/* =========================================================
   TEXT UTILITIES
========================================================= */

function cleanText(value) {

    if (value === null || value === undefined) {
        return "";
    }

    return String(value)
        .replace(/\s+/g, " ")
        .trim();

}


function normalizeSubjectName(subject) {

    const value = cleanText(subject);

    if (!value) {
        return "";

    }

    const key = value.toLowerCase();

    return SUBJECT_ALIASES[key] || value;

}


function normalizeTopicName(topic) {

    return cleanText(topic);

}


/* =========================================================
   CURRICULUM HELPERS
========================================================= */

function getCurriculumSubjects() {

    return Object.keys(NIGERIAN_CURRICULUM)
        .sort((a, b) => a.localeCompare(b));

}


function findCurriculumSubject(subject) {

    const normalized = normalizeSubjectName(subject);

    const exact = Object.keys(NIGERIAN_CURRICULUM)
        .find(item =>
            item.toLowerCase() === normalized.toLowerCase()
        );

    if (exact) {
        return exact;
    }

    return normalized;

}


function getCurriculumTopics(subject) {

    const curriculumSubject =
        findCurriculumSubject(subject);

    return NIGERIAN_CURRICULUM[curriculumSubject] || [];

}


/* =========================================================
   STUDY PLAN
========================================================= */

function getStudyPlan() {

    const possibleKeys = [

        "studyMindPlan",

        "studyData",

        "studyPlan",

        "studyMindStudyPlan"

    ];

    for (const key of possibleKeys) {

        try {

            const raw =
                localStorage.getItem(key);

            if (!raw) {
                continue;
            }

            const parsed =
                JSON.parse(raw);

            if (parsed) {
                return parsed;
            }

        } catch (error) {

            console.warn(
                `Unable to read ${key}`,
                error
            );

        }

    }

    return null;

}


/* =========================================================
   PLAN SUBJECT EXTRACTION
========================================================= */

function getPlanSubjects(plan) {

    if (!plan) {
        return [];
    }

    const subjects = [];

    const possibleArrays = [

        plan.subjects,

        plan.subjectList,

        plan.data?.subjects,

        plan.studyPlan?.subjects,

        plan.schedule?.subjects

    ];

    for (const list of possibleArrays) {

        if (!Array.isArray(list)) {
            continue;
        }

        for (const item of list) {

            if (typeof item === "string") {

                const name =
                    normalizeSubjectName(item);

                if (name) {
                    subjects.push(name);
                }

            }

            else if (
                item &&
                typeof item === "object"
            ) {

                const name =
                    item.subject ||
                    item.name ||
                    item.title;

                if (name) {

                    const normalized =
                        normalizeSubjectName(name);

                    if (normalized) {
                        subjects.push(normalized);
                    }

                }

            }

        }

    }

    return [
        ...new Set(subjects)
    ];

}


/* =========================================================
   TOPICS FROM STUDY PLAN
========================================================= */

function getPlanTopics(plan, selectedSubject) {

    if (!plan) {
        return [];
    }

    const topics = [];

    const normalizedSelectedSubject =
        normalizeSubjectName(selectedSubject);

    const possibleArrays = [

        plan.topics,

        plan.studyTopics,

        plan.studyPlan?.topics,

        plan.data?.topics,

        plan.schedule?.topics

    ];

    for (const list of possibleArrays) {

        if (!Array.isArray(list)) {
            continue;
        }

        for (const item of list) {

            if (typeof item === "string") {

                const topic =
                    normalizeTopicName(item);

                if (topic) {
                    topics.push(topic);
                }

                continue;

            }


            if (
                item &&
                typeof item === "object"
            ) {

                const itemSubject =
                    normalizeSubjectName(
                        item.subject ||
                        item.subjectName ||
                        item.course ||
                        ""
                    );

                const topic =
                    item.topic ||
                    item.name ||
                    item.title;

                if (!topic) {
                    continue;
                }

                /*
                 * If the topic explicitly belongs to a
                 * subject, only include it for that subject.
                 */

                if (
                    itemSubject &&
                    normalizedSelectedSubject &&
                    itemSubject !== normalizedSelectedSubject
                ) {
                    continue;
                }

                topics.push(
                    normalizeTopicName(topic)
                );

            }

        }

    }

    return [
        ...new Set(
            topics.filter(Boolean)
        )
    ];

}


/* =========================================================
   GET AVAILABLE SUBJECTS
========================================================= */

function getAvailableSubjects(plan) {

    const subjects = [

        ...getCurriculumSubjects(),

        ...getPlanSubjects(plan)

    ];

    return [
        ...new Set(
            subjects
                .map(normalizeSubjectName)
                .filter(Boolean)
        )
    ].sort(
        (a, b) => a.localeCompare(b)
    );

}


/* =========================================================
   GET AVAILABLE TOPICS
========================================================= */

function getAvailableTopics(plan, subject) {

    const curriculumTopics =
        getCurriculumTopics(subject);

    const planTopics =
        getPlanTopics(plan, subject);

    return [
        ...new Set([
            ...curriculumTopics,
            ...planTopics
        ])
    ].filter(Boolean);

}


/* =========================================================
   LOAD SUBJECT DROPDOWN
========================================================= */

function loadBattleSetup() {

    const subjectSelect =
        $("subjectSelect");

    const topicSelect =
        $("topicSelect");

    const startButton =
        $("startBattleButton");

    if (!subjectSelect) {

        console.error(
            "computer-battle.js: subjectSelect not found."
        );

        return;

    }

    if (!topicSelect) {

        console.error(
            "computer-battle.js: topicSelect not found."
        );

        return;

    }


    const plan =
        getStudyPlan();

    const subjects =
        getAvailableSubjects(plan);


    subjectSelect.innerHTML = "";


    if (!subjects.length) {

        subjectSelect.innerHTML = `
            <option value="">
                No subjects available
            </option>
        `;

        topicSelect.innerHTML = `
            <option value="">
                No topics available
            </option>
        `;

        if (startButton) {
            startButton.disabled = true;
        }

        return;

    }


    const placeholder =
        document.createElement("option");

    placeholder.value = "";

    placeholder.textContent =
        "Select a subject";

    subjectSelect.appendChild(
        placeholder
    );


    subjects.forEach(subject => {

        const option =
            document.createElement("option");

        option.value = subject;

        option.textContent = subject;

        subjectSelect.appendChild(
            option
        );

    });


    topicSelect.innerHTML = `
        <option value="">
            Select a subject first
        </option>
    `;


    if (startButton) {
        startButton.disabled = true;
    }


    subjectSelect.addEventListener(
        "change",
        updateTopicOptions
    );


    topicSelect.addEventListener(
        "change",
        updateStartButton
    );

}


/* =========================================================
   UPDATE TOPIC DROPDOWN
========================================================= */

function updateTopicOptions() {

    const subjectSelect =
        $("subjectSelect");

    const topicSelect =
        $("topicSelect");

    if (!subjectSelect || !topicSelect) {
        return;
    }


    const selectedSubject =
        normalizeSubjectName(
            subjectSelect.value
        );


    topicSelect.innerHTML = "";


    if (!selectedSubject) {

        topicSelect.innerHTML = `
            <option value="">
                Select a subject first
            </option>
        `;

        updateStartButton();

        return;

    }


    const plan =
        getStudyPlan();

    const topics =
        getAvailableTopics(
            plan,
            selectedSubject
        );


    if (!topics.length) {

        topicSelect.innerHTML = `
            <option value="">
                No curriculum topics available
            </option>
        `;

        updateStartButton();

        return;

    }


    const placeholder =
        document.createElement("option");

    placeholder.value = "";

    placeholder.textContent =
        "Select a topic";

    topicSelect.appendChild(
        placeholder
    );


    topics.forEach(topic => {

        const option =
            document.createElement("option");

        option.value = topic;

        option.textContent = topic;

        topicSelect.appendChild(
            option
        );

    });


    updateStartButton();

}


/* =========================================================
   START BUTTON STATE
========================================================= */

function updateStartButton() {

    const subjectSelect =
        $("subjectSelect");

    const topicSelect =
        $("topicSelect");

    const startButton =
        $("startBattleButton");

    if (
        !subjectSelect ||
        !topicSelect ||
        !startButton
    ) {
        return;
    }


    startButton.disabled = !(
        subjectSelect.value &&
        topicSelect.value
    );

}


/* =========================================================
   ERROR UI
========================================================= */

function showBattleError(message) {

    const error =
        $("battleError");

    if (!error) {
        alert(message);
        return;
    }

    error.textContent =
        cleanText(message);

    error.classList.add("active");

}


function hideBattleError() {

    const error =
        $("battleError");

    if (!error) {
        return;
    }

    error.textContent = "";

    error.classList.remove("active");

}


/* =========================================================
   SCREEN MANAGEMENT
========================================================= */

function showSetup() {

    $("battleSetup")?.classList.remove("hidden");

    $("battleSetup")?.classList.remove("active");

    if ($("battleSetup")) {
        $("battleSetup").style.display = "block";
    }

    if ($("battleLoading")) {
        $("battleLoading").classList.remove("active");
        $("battleLoading").style.display = "none";
    }

    if ($("battleScreen")) {
        $("battleScreen").classList.remove("active");
        $("battleScreen").style.display = "none";
    }

    if ($("battleResults")) {
        $("battleResults").classList.remove("active");
        $("battleResults").style.display = "none";
    }

}


function showLoading() {

    if ($("battleSetup")) {
        $("battleSetup").style.display = "none";
    }

    if ($("battleScreen")) {
        $("battleScreen").style.display = "none";
    }

    if ($("battleResults")) {
        $("battleResults").style.display = "none";
    }

    if ($("battleLoading")) {
        $("battleLoading").classList.add("active");
        $("battleLoading").style.display = "block";
    }

}


function showBattleScreen() {

    if ($("battleSetup")) {
        $("battleSetup").style.display = "none";
    }

    if ($("battleLoading")) {
        $("battleLoading").classList.remove("active");
        $("battleLoading").style.display = "none";
    }

    if ($("battleResults")) {
        $("battleResults").classList.remove("active");
        $("battleResults").style.display = "none";
    }

    if ($("battleScreen")) {
        $("battleScreen").classList.add("active");
        $("battleScreen").style.display = "block";
    }

}


function showResults() {

    if ($("battleSetup")) {
        $("battleSetup").style.display = "none";
    }

    if ($("battleLoading")) {
        $("battleLoading").style.display = "none";
    }

    if ($("battleScreen")) {
        $("battleScreen").classList.remove("active");
        $("battleScreen").style.display = "none";
    }

    if ($("battleResults")) {
        $("battleResults").classList.add("active");
        $("battleResults").style.display = "block";
    }

}


/* =========================================================
   GENERATE RANDOM BATTLE ID
========================================================= */

function createBattleNonce() {

    return [

        Date.now().toString(36),

        Math.random()
            .toString(36)
            .slice(2),

        Math.random()
            .toString(36)
            .slice(2)

    ].join("-");

}


/* =========================================================
   AI REQUEST
========================================================= */

async function generateAIQuestions(
    subject,
    topic
) {

    const normalizedSubject =
        findCurriculumSubject(subject);

    const normalizedTopic =
        normalizeTopicName(topic);


    const curriculumTopics =
        getCurriculumTopics(
            normalizedSubject
        );


    const battleNonce =
        createBattleNonce();


    /*
     * This is deliberately explicit.

     * The AI is instructed that the selected subject
     * is mandatory and that it must not substitute
     * Mathematics or another subject.
     */

    const requestBody = {

        requestType: "computer_battle",

        mode: "computer_battle",

        subject: normalizedSubject,

        topic: normalizedTopic,

        curriculum: "Nigerian Senior Secondary School curriculum",

        curriculumTopics: curriculumTopics,

        numberOfQuestions:
            QUESTIONS_PER_BATTLE,

        questionCount:
            QUESTIONS_PER_BATTLE,

        difficulty: "mixed",

        questionType:
            "multiple_choice",

        optionsPerQuestion: 4,

        randomized: true,

        uniqueQuestions: true,

        battleNonce: battleNonce,

        instructions: [

            "Generate exactly 10 multiple-choice questions.",

            `Every question must be about ${normalizedSubject}.`,

            `Every question must be directly related to ${normalizedTopic}.`,

            "Do not generate Mathematics questions unless Mathematics is the selected subject.",

            "Do not substitute another subject.",

            "Follow the Nigerian Senior Secondary School curriculum.",

            "Use academically appropriate secondary-school level content.",

            "Create a different set of questions for every request.",

            "Do not repeat questions within this battle.",

            "Randomize the correct answer position.",

            "Each question must have exactly four answer options.",

            "Only one answer may be correct.",

            "Return the correct answer clearly.",

            "Do not include explanations unless requested."

        ]

    };


    const response =
        await fetch(
            AI_QUESTION_ENDPOINT,
            {

                method: "POST",

                headers: {
                    "Content-Type":
                        "application/json",

                    "Accept":
                        "application/json"
                },

                cache: "no-store",

                body: JSON.stringify(
                    requestBody
                )

            }
        );


    if (!response.ok) {

        let errorMessage =
            `AI question generation failed (${response.status}).`;

        try {

            const errorData =
                await response.json();

            if (errorData?.error) {

                errorMessage =
                    cleanText(
                        errorData.error
                    );

            }

        } catch {
            // Ignore invalid error JSON.
        }

        throw new Error(
            errorMessage
        );

    }


    const data =
        await response.json();


    return extractQuestionArray(data);

}


/* =========================================================
   EXTRACT QUESTIONS FROM AI RESPONSE
========================================================= */

function extractQuestionArray(data) {

    if (Array.isArray(data)) {
        return data;
    }


    if (!data || typeof data !== "object") {
        return [];
    }


    const possibleArrays = [

        data.questions,

        data.data,

        data.results,

        data.items,

        data.output?.questions,

        data.response?.questions,

        data.result?.questions

    ];


    for (const value of possibleArrays) {

        if (Array.isArray(value)) {
            return value;
        }

    }


    /*
     * Some models return JSON inside a text field.
     */

    const possibleTextFields = [

        data.text,

        data.content,

        data.output,

        data.response,

        data.result

    ];


    for (const text of possibleTextFields) {

        if (typeof text !== "string") {
            continue;
        }

        const parsed =
            parseQuestionsFromText(text);

        if (parsed.length) {
            return parsed;
        }

    }


    return [];

}


/* =========================================================
   PARSE JSON FROM AI TEXT
========================================================= */

function parseQuestionsFromText(text) {

    const cleaned =
        text
            .replace(/```json/gi, "")
            .replace(/```/g, "")
            .trim();


    try {

        const parsed =
            JSON.parse(cleaned);

        if (Array.isArray(parsed)) {
            return parsed;
        }

        if (
            parsed &&
            Array.isArray(parsed.questions)
        ) {
            return parsed.questions;
        }

    } catch {
        // Continue to bracket extraction.
    }


    const firstArray =
        cleaned.indexOf("[");

    const lastArray =
        cleaned.lastIndexOf("]");


    if (
        firstArray !== -1 &&
        lastArray > firstArray
    ) {

        try {

            const parsed =
                JSON.parse(
                    cleaned.slice(
                        firstArray,
                        lastArray + 1
                    )
                );

            if (Array.isArray(parsed)) {
                return parsed;
            }

        } catch {
            // Invalid embedded JSON.
        }

    }


    return [];

}


/* =========================================================
   QUESTION NORMALIZATION
========================================================= */

function normalizeQuestion(
    raw,
    subject,
    topic
) {

    if (!raw || typeof raw !== "object") {
        return null;
    }


    const questionText =
        cleanText(
            raw.question ||
            raw.questionText ||
            raw.text ||
            raw.prompt
        );


    if (!questionText) {
        return null;
    }


    let options =
        raw.options ||
        raw.answers ||
        raw.choices ||
        raw.answerOptions;


    if (
        !Array.isArray(options) ||
        options.length < 4
    ) {
        return null;
    }


    options = options
        .map(option => {

            if (
                typeof option === "string"
            ) {
                return cleanText(option);
            }

            if (
                option &&
                typeof option === "object"
            ) {

                return cleanText(
                    option.text ||
                    option.answer ||
                    option.label ||
                    option.value
                );

            }

            return "";

        })
        .filter(Boolean);


    if (options.length < 4) {
        return null;
    }


    options =
        options.slice(0, 4);


    /*
     * Remove duplicate answer options.
     */

    const uniqueOptions =
        [
            ...new Set(
                options.map(
                    option =>
                        option.toLowerCase()
                )
            )
        ];


    if (uniqueOptions.length !== 4) {
        return null;
    }


    const rawAnswer =
        raw.correctAnswer ??
        raw.correct ??
        raw.answer ??
        raw.correctOption ??
        raw.correctIndex;


    let correctIndex = -1;


    if (
        typeof rawAnswer === "number"
    ) {

        if (
            rawAnswer >= 0 &&
            rawAnswer < 4
        ) {

            correctIndex =
                rawAnswer;

        }

        else if (
            rawAnswer >= 1 &&
            rawAnswer <= 4
        ) {

            correctIndex =
                rawAnswer - 1;

        }

    }


    if (
        typeof rawAnswer === "string"
    ) {

        const answer =
            cleanText(rawAnswer);


        const upper =
            answer.toUpperCase();


        if (/^[A-D]$/.test(upper)) {

            correctIndex =
                "ABCD".indexOf(upper);

        }

        else {

            const exactIndex =
                options.findIndex(
                    option =>
                        option.toLowerCase() ===
                        answer.toLowerCase()
                );

            if (exactIndex !== -1) {
                correctIndex = exactIndex;
            }

        }

    }


    if (
        correctIndex < 0 ||
        correctIndex > 3
    ) {

        /*
         * Some APIs return:
         *
         * answer: {
         *   index: 2
         * }
         */

        if (
            rawAnswer &&
            typeof rawAnswer === "object"
        ) {

            const index =
                rawAnswer.index ??
                rawAnswer.position;

            if (
                typeof index === "number"
            ) {

                if (
                    index >= 0 &&
                    index < 4
                ) {
                    correctIndex = index;
                }

                else if (
                    index >= 1 &&
                    index <= 4
                ) {
                    correctIndex = index - 1;
                }

            }

        }

    }


    if (
        correctIndex < 0 ||
        correctIndex > 3
    ) {
        return null;
    }


    return {

        question:
            questionText,

        options:

            options,

        correctIndex:

            correctIndex,

        subject:

            normalizeSubjectName(
                raw.subject ||
                subject
            ),

        topic:

            cleanText(
                raw.topic ||
                raw.questionTopic ||
                topic
            )

    };

}


/* =========================================================
   BASIC QUESTION VALIDATION
========================================================= */

function validateQuestion(
    question,
    subject,
    topic
) {

    if (!question) {
        return false;
    }


    if (
        !question.question ||
        !Array.isArray(question.options)
    ) {
        return false;
    }


    if (
        question.options.length !== 4
    ) {
        return false;
    }


    if (
        question.correctIndex < 0 ||
        question.correctIndex > 3
    ) {
        return false;
    }


    /*
     * The API is asked to provide subject/topic metadata.

     * If metadata exists, verify it.
     *
     * We don't reject a question solely because the model
     * omitted metadata, because the question itself may still
     * be valid.
     */

    if (question.subject) {

        const expected =
            normalizeSubjectName(subject);

        const actual =
            normalizeSubjectName(
                question.subject
            );


        if (
            actual &&
            expected &&
            actual !== expected
        ) {

            console.warn(
                "Rejected question from wrong subject:",
                actual,
                "expected:",
                expected
            );

            return false;

        }

    }


    if (question.topic) {

        const expectedTopic =
            normalizeTopicName(topic)
                .toLowerCase();

        const actualTopic =
            normalizeTopicName(
                question.topic
            ).toLowerCase();


        /*
         * If the AI explicitly labels a question with a
         * different topic, reject it.
         */

        if (
            actualTopic &&
            expectedTopic &&
            actualTopic !== expectedTopic
        ) {

            console.warn(
                "Rejected question from wrong topic:",
                actualTopic,
                "expected:",
                expectedTopic
            );

            return false;

        }

    }


    return true;

}


/* =========================================================
   PREPARE AI QUESTIONS

   IMPORTANT:
   We do NOT have a fallback question bank.

   If the AI doesn't provide 10 valid questions,
   the battle does not silently switch to Math.
========================================================= */

function prepareQuestions(
    rawQuestions,
    subject,
    topic
) {

    const normalized = [];


    for (const raw of rawQuestions) {

        const question =
            normalizeQuestion(
                raw,
                subject,
                topic
            );


        if (
            !validateQuestion(
                question,
                subject,
                topic
            )
        ) {
            continue;
        }


        normalized.push(question);

    }


    /*
     * Remove duplicate questions.
     */

    const unique = [];

    const seen =
        new Set();


    for (const question of normalized) {

        const key =
            question.question
                .toLowerCase()
                .replace(/\s+/g, " ")
                .trim();


        if (seen.has(key)) {
            continue;
        }


        seen.add(key);

        unique.push(question);

    }


    /*
     * Randomize the questions.
     */

    shuffleArray(unique);


    /*
     * We REQUIRE exactly 10 AI-generated questions.

     * No Math fallback.
     * No hard-coded fallback.
     */

    if (
        unique.length <
        QUESTIONS_PER_BATTLE
    ) {

        throw new Error(
            `The AI generated only ${unique.length} valid questions for ${subject} — ${topic}. Please try again.`
        );

    }


    return unique.slice(
        0,
        QUESTIONS_PER_BATTLE
    );

}


/* =========================================================
   RANDOM SHUFFLE
========================================================= */

function shuffleArray(array) {

    for (
        let i = array.length - 1;
        i > 0;
        i--
    ) {

        const j =
            Math.floor(
                Math.random() * (i + 1)
            );


        [
            array[i],
            array[j]
        ] = [
            array[j],
            array[i]
        ];

    }


    return array;

}


/* =========================================================
   RANDOMIZE ANSWERS

   This prevents the correct answer from always being
   in the same position.
========================================================= */

function randomizeQuestionAnswers(question) {

    const correctAnswer =
        question.options[
            question.correctIndex
        ];


    const shuffled =
        [...question.options];


    shuffleArray(shuffled);


    question.options =
        shuffled;


    question.correctIndex =
        shuffled.indexOf(
            correctAnswer
        );


    return question;

}


/* =========================================================
   RANDOMIZE ENTIRE BATTLE
========================================================= */

function randomizeBattleQuestions(
    questions
) {

    shuffleArray(questions);


    questions.forEach(question => {

        randomizeQuestionAnswers(
            question
        );

    });


    return questions;

}


/* =========================================================
   START COMPUTER BATTLE
========================================================= */

async function startComputerBattle() {

    hideBattleError();


    const subjectSelect =
        $("subjectSelect");

    const topicSelect =
        $("topicSelect");

    const startButton =
        $("startBattleButton");


    if (
        !subjectSelect ||
        !topicSelect
    ) {

        showBattleError(
            "The battle setup could not be loaded correctly."
        );

        return;

    }


    const subject =
        normalizeSubjectName(
            subjectSelect.value
        );


    const topic =
        normalizeTopicName(
            topicSelect.value
        );


    if (!subject) {

        showBattleError(
            "Please select a subject."
        );

        return;

    }


    if (!topic) {

        showBattleError(
            "Please select a topic."
        );

        return;

    }


    if (startButton) {
        startButton.disabled = true;
        startButton.textContent =
            "Generating Battle...";
    }


    showLoading();


    try {

        /*
         * Get authenticated user.
         */

        const client =
            await waitForSupabaseClient();


        if (!client) {

            throw new Error(
                "StudyMind authentication is not ready. Please refresh the page and try again."
            );

        }


        const {
            data: {
                user
            },
            error
        } =
            await client.auth.getUser();


        if (error) {
            throw error;
        }


        if (!user) {

            throw new Error(
                "You must be logged in to play Computer Battle."
            );

        }


        battleState = {

            user: user,

            subject: subject,

            topic: topic,

            questions: [],

            currentQuestionIndex: 0,

            playerScore: 0,

            computerScore: 0,

            timer: null,

            timeRemaining:
                QUESTION_TIME_LIMIT,

            answered: false,

            battleStarted: false,

            battleId:
                createBattleNonce()

        };


        /*
         * Ask the AI for a completely new set.
         */

        const rawQuestions =
            await generateAIQuestions(
                subject,
                topic
            );


        /*
         * Validate and prepare them.
         */

        const questions =
            prepareQuestions(
                rawQuestions,
                subject,
                topic
            );


        /*
         * Randomize the final set and answer positions.
         */

        randomizeBattleQuestions(
            questions
        );


        battleState.questions =
            questions;


        battleState.battleStarted =
            true;


        showBattleScreen();


        updateBattleScore();

        displayCurrentQuestion();


    } catch (error) {

        console.error(
            "Computer Battle error:",
            error
        );


        /*
         * IMPORTANT:
         * We do NOT provide Math questions here.
         */

        showSetup();


        showBattleError(
            error?.message ||
            "The AI could not generate your battle questions. Please try again."
        );


    } finally {

        if (startButton) {

            startButton.disabled = false;

            startButton.textContent =
                "⚔️ Start Battle";

        }

    }

}


/* =========================================================
   DISPLAY CURRENT QUESTION
========================================================= */

function displayCurrentQuestion() {

    stopTimer();


    const question =
        battleState.questions[
            battleState.currentQuestionIndex
        ];


    if (!question) {

        finishBattle();

        return;

    }


    battleState.answered = false;

    battleState.timeRemaining =
        QUESTION_TIME_LIMIT;


    const questionNumber =
        battleState.currentQuestionIndex + 1;


    const roundNumber =
        $("roundNumber");

    const questionTopic =
        $("questionTopic");

    const questionText =
        $("questionText");

    const answerGrid =
        $("answerGrid");

    const timerNumber =
        $("timerNumber");

    const timerContainer =
        $("timerContainer");

    const progressBar =
        $("battleProgressBar");

    const feedback =
        $("battleFeedback");


    if (roundNumber) {

        roundNumber.textContent =
            `Question ${questionNumber} of ${QUESTIONS_PER_BATTLE}`;

    }


    if (questionTopic) {

        questionTopic.textContent =
            `${battleState.subject} • ${battleState.topic}`;

    }


    if (questionText) {

        questionText.textContent =
            question.question;

    }


    if (timerNumber) {

        timerNumber.textContent =
            QUESTION_TIME_LIMIT;

    }


    if (timerContainer) {

        timerContainer.classList.remove(
            "warning",
            "danger"
        );

    }


    if (feedback) {

        feedback.textContent = "";

    }


    if (progressBar) {

        const percentage =
            (
                battleState.currentQuestionIndex /
                QUESTIONS_PER_BATTLE
            ) * 100;


        progressBar.style.width =
            `${percentage}%`;

    }


    if (!answerGrid) {
        return;
    }


    answerGrid.innerHTML = "";


    question.options.forEach(
        (option, index) => {

            const button =
                document.createElement(
                    "button"
                );


            button.type =
                "button";

            button.className =
                "answer-button";


            const letter =
                document.createElement(
                    "span"
                );


            letter.className =
                "answer-letter";


            letter.textContent =
                "ABCD"[index];


            const text =
                document.createTextNode(
                    option
                );


            button.appendChild(
                letter
            );

            button.appendChild(
                text
            );


            button.addEventListener(
                "click",
                () => {

                    handleAnswer(
                        index,
                        button
                    );

                }
            );


            answerGrid.appendChild(
                button
            );

        }
    );


    startTimer();

}


/* =========================================================
   TIMER
========================================================= */

function startTimer() {

    stopTimer();


    updateTimerDisplay();


    battleState.timer =
        setInterval(() => {

            if (
                battleState.answered
            ) {
                return;
            }


            battleState.timeRemaining--;


            updateTimerDisplay();


            if (
                battleState.timeRemaining <= 0
            ) {

                stopTimer();

                handleTimeout();

            }

        }, 1000);

}


/* =========================================================
   UPDATE TIMER
========================================================= */

function updateTimerDisplay() {

    const timerNumber =
        $("timerNumber");

    const timerContainer =
        $("timerContainer");


    if (timerNumber) {

        timerNumber.textContent =
            Math.max(
                0,
                battleState.timeRemaining
            );

    }


    if (!timerContainer) {
        return;
    }


    timerContainer.classList.remove(
        "warning",
        "danger"
    );


    if (
        battleState.timeRemaining <= 5
    ) {

        timerContainer.classList.add(
            "danger"
        );

    }

    else if (
        battleState.timeRemaining <= 8
    ) {

        timerContainer.classList.add(
            "warning"
        );

    }

}


/* =========================================================
   STOP TIMER
========================================================= */

function stopTimer() {

    if (battleState.timer) {

        clearInterval(
            battleState.timer
        );

        battleState.timer = null;

    }

}


/* =========================================================
   HANDLE ANSWER
========================================================= */

function handleAnswer(
    selectedIndex,
    selectedButton
) {

    if (
        battleState.answered
    ) {
        return;
    }


    battleState.answered =
        true;


    stopTimer();


    const question =
        battleState.questions[
            battleState.currentQuestionIndex
        ];


    if (!question) {
        return;
    }


    const correctIndex =
        question.correctIndex;


    const answerButtons =
        document.querySelectorAll(
            "#answerGrid .answer-button"
        );


    answerButtons.forEach(
        (button, index) => {

            button.disabled =
                true;


            if (
                index === correctIndex
            ) {

                button.classList.add(
                    "correct"
                );

            }

        }
    );


    const feedback =
        $("battleFeedback");


    if (
        selectedIndex === correctIndex
    ) {

        battleState.playerScore++;


        if (selectedButton) {

            selectedButton.classList.add(
                "correct"
            );

        }


        if (feedback) {

            feedback.textContent =
                "✓ Correct!";

        }

    }

    else {

        if (selectedButton) {

            selectedButton.classList.add(
                "incorrect"
            );

        }


        if (feedback) {

            feedback.textContent =
                "✗ Incorrect";

        }

    }


    updateBattleScore();


    /*
     * The computer answers after the player.
     */

    setTimeout(
        computerTurn,
        700
    );

}


/* =========================================================
   TIMEOUT
========================================================= */

function handleTimeout() {

    if (
        battleState.answered
    ) {
        return;
    }


    battleState.answered =
        true;


    const question =
        battleState.questions[
            battleState.currentQuestionIndex
        ];


    if (!question) {
        return;
    }


    const answerButtons =
        document.querySelectorAll(
            "#answerGrid .answer-button"
        );


    answerButtons.forEach(
        (button, index) => {

            button.disabled =
                true;


            if (
                index === question.correctIndex
            ) {

                button.classList.add(
                    "correct"
                );

            }

        }
    );


    const feedback =
        $("battleFeedback");


    if (feedback) {

        feedback.textContent =
            "⏱ Time's up!";

    }


    /*
     * Player does not receive a point.
     */

    setTimeout(
        computerTurn,
        700
    );

}


/* =========================================================
   COMPUTER TURN
========================================================= */

function computerTurn() {

    const question =
        battleState.questions[
            battleState.currentQuestionIndex
        ];


    if (!question) {
        finishBattle();
        return;
    }


    /*
     * The computer gets a probability of answering
     * correctly.

     * This is gameplay logic, not a question source.
     */

    const difficulty =
        getComputerDifficulty();


    const correctProbability =
        difficulty;


    if (
        Math.random() <
        correctProbability
    ) {

        battleState.computerScore++;

    }


    updateBattleScore();


    setTimeout(
        nextQuestion,
        500
    );

}


/* =========================================================
   COMPUTER DIFFICULTY
========================================================= */

function getComputerDifficulty() {

    /*
     * Keeps the computer competitive without
     * generating or storing questions.
     */

    return 0.60;

}


/* =========================================================
   NEXT QUESTION
========================================================= */

function nextQuestion() {

    battleState.currentQuestionIndex++;


    if (
        battleState.currentQuestionIndex >=
        QUESTIONS_PER_BATTLE
    ) {

        finishBattle();

        return;

    }


    displayCurrentQuestion();

}


/* =========================================================
   UPDATE SCORE
========================================================= */

function updateBattleScore() {

    const playerScore =
        $("playerScore");

    const computerScore =
        $("computerScore");


    if (playerScore) {

        playerScore.textContent =
            battleState.playerScore;

    }


    if (computerScore) {

        computerScore.textContent =
            battleState.computerScore;

    }

}


/* =========================================================
   CALCULATE BATTLE POINTS
========================================================= */

function calculateBattlePoints(
    result
) {

    if (result === "win") {

        return 25;

    }


    if (result === "draw") {

        return 10;

    }


    return 5;

}


/* =========================================================
   FINISH BATTLE
========================================================= */

async function finishBattle() {

    stopTimer();


    const progressBar =
        $("battleProgressBar");


    if (progressBar) {
        progressBar.style.width = "100%";
    }


    const playerScore =
        battleState.playerScore;

    const computerScore =
        battleState.computerScore;


    let result;


    if (
        playerScore >
        computerScore
    ) {

        result = "win";

    }

    else if (
        playerScore <
        computerScore
    ) {

        result = "loss";

    }

    else {

        result = "draw";

    }


    const points =
        calculateBattlePoints(
            result
        );


    await saveBattleResult(
        result,
        points
    );


    displayResults(
        result,
        points
    );

}


/* =========================================================
   DISPLAY RESULTS
========================================================= */

function displayResults(
    result,
    points
) {

    const resultIcon =
        $("resultIcon");

    const resultTitle =
        $("resultTitle");

    const resultSummary =
        $("resultSummary");

    const finalPlayerScore =
        $("finalPlayerScore");

    const finalComputerScore =
        $("finalComputerScore");

    const battlePointsEarned =
        $("battlePointsEarned");

    const battleResultMessage =
        $("battleResultMessage");


    if (finalPlayerScore) {

        finalPlayerScore.textContent =
            battleState.playerScore;

    }


    if (finalComputerScore) {

        finalComputerScore.textContent =
            battleState.computerScore;

    }


    if (battlePointsEarned) {

        battlePointsEarned.textContent =
            points;

    }


    if (result === "win") {

        if (resultIcon) {
            resultIcon.textContent = "🏆";
        }

        if (resultTitle) {
            resultTitle.textContent =
                "Victory!";
        }

        if (resultSummary) {

            resultSummary.textContent =
                `You defeated the computer in ${battleState.subject}.`;

        }

        if (battleResultMessage) {

            battleResultMessage.textContent =
                `Excellent work. You scored ${battleState.playerScore} out of ${QUESTIONS_PER_BATTLE} and earned ${points} Battle Points.`;

        }

    }

    else if (result === "loss") {

        if (resultIcon) {
            resultIcon.textContent = "🤖";
        }

        if (resultTitle) {
            resultTitle.textContent =
                "Computer Wins";
        }

        if (resultSummary) {

            resultSummary.textContent =
                `The computer won this ${battleState.subject} battle.`;

        }

        if (battleResultMessage) {

            battleResultMessage.textContent =
                `You scored ${battleState.playerScore} out of ${QUESTIONS_PER_BATTLE}. Keep studying and try another battle.`;

        }

    }

    else {

        if (resultIcon) {
            resultIcon.textContent = "🤝";
        }

        if (resultTitle) {
            resultTitle.textContent =
                "Draw!";
        }

        if (resultSummary) {

            resultSummary.textContent =
                "Neither player managed to take the win.";

        }

        if (battleResultMessage) {

            battleResultMessage.textContent =
                `You both scored ${battleState.playerScore}. You earned ${points} Battle Points.`;

        }

    }


    showResults();

}


/* =========================================================
   SAVE BATTLE RESULT
========================================================= */

async function saveBattleResult(
    result,
    points
) {

    const client =
        getComputerBattleSupabase();


    if (
        !client ||
        !battleState.user
    ) {

        console.warn(
            "Unable to save battle result: Supabase unavailable."
        );

        return;

    }


    try {

        const userId =
            battleState.user.id;


        const displayName =
            battleState.user.user_metadata
                ?.display_name ||
            battleState.user.user_metadata
                ?.full_name ||
            battleState.user.email?.split("@")[0] ||
            "StudyMind Player";


        const {
            data: existing,
            error: selectError
        } =
            await client
                .from("game_leaderboard")
                .select(
                    "user_id,display_name,battle_points,wins,losses,draws,battles_played"
                )
                .eq(
                    "user_id",
                    userId
                )
                .maybeSingle();


        if (selectError) {

            console.warn(
                "Leaderboard lookup failed:",
                selectError
            );

            return;

        }


        const current =
            existing || {

                user_id: userId,

                display_name:
                    displayName,

                battle_points: 0,

                wins: 0,

                losses: 0,

                draws: 0,

                battles_played: 0

            };


        const update = {

            user_id: userId,

            display_name:
                current.display_name ||
                displayName,

            battle_points:
                Number(
                    current.battle_points || 0
                ) + points,

            wins:
                Number(
                    current.wins || 0
                ) +
                (
                    result === "win"
                        ? 1
                        : 0
                ),

            losses:
                Number(
                    current.losses || 0
                ) +
                (
                    result === "loss"
                        ? 1
                        : 0
                ),

            draws:
                Number(
                    current.draws || 0
                ) +
                (
                    result === "draw"
                        ? 1
                        : 0
                ),

            battles_played:
                Number(
                    current.battles_played || 0
                ) + 1,

            updated_at:
                new Date().toISOString()

        };


        const {
            error: upsertError
        } =
            await client
                .from("game_leaderboard")
                .upsert(
                    update,
                    {
                        onConflict:
                            "user_id"
                    }
                );


        if (upsertError) {

            console.warn(
                "Leaderboard update failed:",
                upsertError
            );

        }

    }

    catch (error) {

        console.warn(
            "Battle result save error:",
            error
        );

    }

}


/* =========================================================
   FREE BATTLE COUNTER
========================================================= */

function getBattleCountKey() {

    const userId =
        battleState.user?.id ||
        "guest";


    return `studyMindComputerBattles_${userId}`;

}


function getBattleCount() {

    try {

        return Number(
            localStorage.getItem(
                getBattleCountKey()
            ) || 0
        );

    } catch {

        return 0;

    }

}


function incrementBattleCount() {

    try {

        const next =
            getBattleCount() + 1;


        localStorage.setItem(
            getBattleCountKey(),
            String(next)
        );


        return next;

    } catch {

        return 0;

    }

}


/* =========================================================
   PLAY AGAIN
========================================================= */

async function playAgain() {

    showSetup();


    const subjectSelect =
        $("subjectSelect");

    const topicSelect =
        $("topicSelect");


    if (
        subjectSelect &&
        battleState.subject
    ) {

        subjectSelect.value =
            battleState.subject;


        updateTopicOptions();


        if (
            topicSelect &&
            battleState.topic
        ) {

            const matchingOption =
                Array.from(
                    topicSelect.options
                ).find(
                    option =>
                        option.value ===
                        battleState.topic
                );


            if (matchingOption) {

                topicSelect.value =
                    battleState.topic;

            }

        }

    }


    updateStartButton();


    /*
     * IMPORTANT:
     * When the user starts again, startComputerBattle()
     * creates a NEW battle nonce and requests a NEW AI
     * question set.
     */

}


/* =========================================================
   RETURN TO GAME MODE
========================================================= */

function returnToGameMode() {

    window.location.href =
        "game-mode.html";

}


/* =========================================================
   AUTHENTICATION CHECK
========================================================= */

async function verifyComputerBattleUser() {

    const client =
        await waitForSupabaseClient();


    if (!client) {

        throw new Error(
            "Supabase client could not be loaded."
        );

    }


    const {
        data: {
            user
        },
        error
    } =
        await client.auth.getUser();


    if (error) {
        throw error;
    }


    if (!user) {

        throw new Error(
            "You must be logged in to play Computer Battle."
        );

    }


    battleState.user =
        user;


    return user;

}


/* =========================================================
   INITIALIZATION
========================================================= */

async function initializeComputerBattle() {

    console.log(
        "StudyMind Computer Battle initializing..."
    );


    const subjectSelect =
        $("subjectSelect");


    if (!subjectSelect) {

        console.error(
            "Computer Battle HTML elements were not found."
        );

        return;

    }


    try {

        await verifyComputerBattleUser();


        loadBattleSetup();


        console.log(
            "Computer Battle initialized successfully."
        );


    }

    catch (error) {

        console.error(
            "Computer Battle authentication error:",
            error
        );


        showBattleError(
            error?.message ||
            "Unable to initialize Computer Battle."
        );

    }

}


/* =========================================================
   GLOBAL FUNCTIONS
========================================================= */

window.startComputerBattle =
    startComputerBattle;

window.playAgain =
    playAgain;

window.returnToGameMode =
    returnToGameMode;

window.updateTopicOptions =
    updateTopicOptions;


/* =========================================================
   DOM READY
========================================================= */

if (
    document.readyState ===
    "loading"
) {

    document.addEventListener(
        "DOMContentLoaded",
        initializeComputerBattle
    );

}

else {

    initializeComputerBattle();

}


/* =========================================================
   DEBUG HELPERS

   These make it easier to diagnose the page from
   the browser console without exposing anything sensitive.
========================================================= */

window.studyMindComputerBattle =
    {

        getState() {

            return {
                subject:
                    battleState.subject,

                topic:
                    battleState.topic,

                questionCount:
                    battleState.questions.length,

                currentQuestion:
                    battleState.currentQuestionIndex + 1,

                playerScore:
                    battleState.playerScore,

                computerScore:
                    battleState.computerScore,

                battleStarted:
                    battleState.battleStarted

            };

        },


        getCurriculumSubjects() {

            return getCurriculumSubjects();

        },


        getCurriculumTopics(subject) {

            return getCurriculumTopics(
                subject
            );

        }

    };
